alias ..='cd ..'
alias ~='cd ~'
alias s='source'
alias v='vim'
# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias cls='clear; neofetch'
alias cla='clear'
alias e='exit'
alias code='codium'
